export default {
  LOGIN_REQUESTING : "LOGIN_REQUESTING",

  RUN_TASK_REQUESTING: 'RUN_TASK_REQUESTING',
  RUN_TASK_SUCCESS: 'RUN_TASK_SUCCESS',
  RUN_TASK_FAIL: 'RUN_TASK_FAIL',

  GET_TASK_REQUESTING: 'GET_TASK_REQUESTING',
  GET_TASK_SUCCESS: 'GET_TASK_SUCCESS',
  GET_TASK_FAIL: 'GET_TASK_FAIL',

  CREATE_TASK_REQUESTING: 'CREATE_TASK_REQUESTING',
  CREATE_TASK_SUCCESS: 'CREATE_TASK_SUCCESS',
  CREATE_TASK_FAIL: 'CREATE_TASK_FAIL',

  UPDATE_TASK_REQUESTING: 'UPDATE_TASK_REQUESTING',
  UPDATE_TASK_SUCCESS: 'UPDATE_TASK_SUCCESS',
  UPDATE_TASK_FAIL: 'UPDATE_TASK_FAIL',

  DELETE_TASK_REQUESTING: 'DELETE_TASK_REQUESTING',
  DELETE_TASK_SUCCESS: 'DELETE_TASK_SUCCESS',
  DELETE_TASK_FAIL: 'DELETE_TASK_FAIL',
}