export const loginURL = "/login"
export const registerURL = "/register"
export const adminLayout = "/launcher"
export const history = "/history"
export const dashBoard = "/dashboard"
export const schedule = "/schedule"
export const historyURL = adminLayout + history
export const performance = "/performance"
export const performanceURL = adminLayout+performance
export const security = "/security"
export const sast = "/sast"
export const cloc = "/cloc"
export const style = "/style"
export const dast = "/dast"
export const dastAPIScan = "/dast/api"
export const historyStyleURL = adminLayout + sast + history
export const historyClocURL = adminLayout + cloc + history
export const scheduleStyleURL = adminLayout + sast + schedule
export const historyDastURL = adminLayout + dast + history
export const securityURL = adminLayout + security
export const sastURL = adminLayout + sast
export const styleURL = adminLayout + style
export const detail = "/scandetail/id"
export const detailDast = "/dastdetail/id"
export const detailCloc = "/locdetail/result"
export const urlMonitoring = "/monitoring"
export const historyUrlMonitoring = adminLayout + urlMonitoring+history
export const detailUrlMonitoring = "/monitoringurl/detail"

export const autoTest = "/autotest"
export const historyAutoTest = adminLayout + autoTest + history
export const logsAutoTest = "/autotestlogs/id"
